add hw8
Hotckiss/Java-1 pull request #12
Opened 2017-11-28 22:33 UTC by Hotckiss

add hw8

2017-12-23 20:07 UTC, yurii-litvinov requested changes

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Calculator.java
> +		    else {
Тут с отступами что-то пошло не так

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/MyQueue.java
> +    private Node tail = null;
Они ведь и так null

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/MyQueue.java
> +        Node next = null;
Тут они не только и так null, но и явно инициализируются в конструкторе

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/MyQueue.java
> +        Node next = null;
Кстати, нелишне бы и тут модификаторы видимости

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Calculator.java
> +     * Method that evaluates expressino in reversed polish notation
expressino, опечатка

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Calculator.java
> +                case '9':
Сурово :) Что-нибудь с if-ами и множествами символов могло бы быть элегантнее

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Calculator.java
> +        Tok t;
Могло бы быть объявлено внутри while-а

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Calculator.java
> +        Tok b;
Эти штуки тоже можно было бы объявить внутри цикла и инициализировать прямо в месте объявления, это ж не Си :)

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Calculator.java
> +                        state = State.PARSE_ERROR;
state --- локальная переменная, так что присваивать ей значение перед тем, как бросить исключение довольно бесполезно

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Calculator.java
> +                    if (state.ordinal() == State.WAIT_SUFFIX.ordinal()) {
Зачем ordinal()?

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Calculator.java
> +        }
Вообще, алгоритм сортировочной станции обычно обрабатывает скобки не как операторы, а отдельно, это позволяет не возиться с состояниями и вообще особо о скобках не думать. Обычно оно записывается раза в полтора короче

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Calculator.java
> +            t = source.pop();
Мм, `Tok t = source.pop();`

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/MyQueue.java
> +public class MyQueue {
Если она называется MyQueue, я б ожидал, что она будет генериком. Или назвал бы её TokenQueue

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/MyQueue.java
> +    private class Node {
static?

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/MyStack.java
> +    }
Копипаст немного

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Tok.java
> +public class Tok {
Я б назвал Token

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Tok.java
> +    private int op = 0;
Оно и так будет 0

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Tok.java
> +    public enum Tokid { TOK_OP, TOK_NUM };
Я б назвал TokenId

2017-12-23 20:07 UTC, yurii-litvinov commented on MyCalculator/src/test/java/ru/spbau/kirilenko/hw8MyCalculator/CalculatorTest.java
> +        }
IDEA утверждает, что это копипаст, и предлагает сделать отдельный метод. Я бы с ней согласился

2017-12-23 20:14 UTC, Hotckiss commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Calculator.java
> +        }
Просто у меня видимо много ифов где вылетает исключение, но на самом деле там разные ошибки - как раз когда не хватает ( или операнда или ), поэтому длинно вышло

2017-12-23 20:54 UTC, yurii-litvinov commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/Calculator.java
> +        }
Угу. В любом случае, это можно не править

2017-12-24 16:53 UTC, Hotckiss commented on MyCalculator/src/test/java/ru/spbau/kirilenko/hw8MyCalculator/CalculatorTest.java
> +        }
Добавил метод

2017-12-24 16:54 UTC, Hotckiss commented on MyCalculator/src/main/java/ru/spbau/kirilenko/hw8MyCalculator/MyStack.java
> +    }
А это исправляется без создания отдельного класса Node общего для стека и очереди? Я это не исправил, потому что тогда пришлось бы добавлять get/set и тесты с доками)

2018-01-03 19:02 UTC, merged