hw2matrix
Hotckiss/Java-1 pull request #4
Opened 2017-09-24 13:13 UTC by Hotckiss

gradle

2017-10-16 12:35 UTC, yurii-litvinov requested changes
Без .gitignore неудобно выкладывать, наверное.

В целом всё ок, но есть что улучшить.

2017-10-16 12:35 UTC, yurii-litvinov commented on hw2Gradle/src/main/java/ru/spbau/kirilenko/hw2Matrix/Matrix.java
> +import java.util.ArrayList;
IDEA говорит, что этот import не нужен

2017-10-16 12:35 UTC, yurii-litvinov commented on hw2Gradle/src/main/java/ru/spbau/kirilenko/hw2Matrix/Matrix.java
> + *
Хмм, обычно комментарии пишут в виде
```java
/**
 * A class that stores an odd square matrix of integers and allows to sort it and get it in spiral order
 */
```
И дальше у Вас так, а тут нет :)

2017-10-16 12:35 UTC, yurii-litvinov commented on hw2Gradle/src/main/java/ru/spbau/kirilenko/hw2Matrix/Matrix.java
> +    private int size;
Массив сам знает свой размер, так что эту штуку можно не хранить. Особенно если класс гарантирует исполнение инварианта, что все размеры массивов по всем размерностям одинаковы.

2017-10-16 12:35 UTC, yurii-litvinov commented on hw2Gradle/src/main/java/ru/spbau/kirilenko/hw2Matrix/Matrix.java
> +        Arrays.sort(this.matrix, (int[] col1, int[] col2)->{ return Integer.compare(col1[0], col2[0]) ; } );
Можно просто `(int[] col1, int[] col2) -> Integer.compare(col1[0], col2[0])`, а можно ещё проще: `Comparator.comparingInt(col -> col[0])`. Кстати, вокруг стрелочки обычно ставятся пробелы

2017-10-16 12:35 UTC, yurii-litvinov commented on hw2Gradle/src/main/java/ru/spbau/kirilenko/hw2Matrix/Matrix.java
> +     * This method walks around the matrix from it's center NON-clockwise and returns elements in spiral order
NON-clockwise --- counterclockwise?

2017-10-16 12:35 UTC, yurii-litvinov commented on hw2Gradle/src/main/java/ru/spbau/kirilenko/hw2Matrix/Matrix.java
> +        int xs = size / 2, ys = size / 2, currentLength = 1, position = 0;
Каждую переменную лучше объявлять на своей строке, так будет лучше видно, где кто объявляется и какого он типа. Для xs и ys надо бы придумать более говорящие имена

2017-10-16 12:35 UTC, yurii-litvinov commented on hw2Gradle/src/main/java/ru/spbau/kirilenko/hw2Matrix/Matrix.java
> +            if (!type) {
Судя по использованию, type задаёт направление, так что лучше его сделать enum-ом из двух элементов, чем bool-ом. Так хоть не придётся гадать, что значит true или false. Ну и тоже назвать более говоряще. Хотя писать получится больше (объявить тип, инвертировать значение), но читаемость программы того стоит.

2017-10-16 12:35 UTC, yurii-litvinov commented on hw2Gradle/src/test/java/ru/spbau/kirilenko/hw2MatrixTest/MatrixTest.java
> +        Matrix matrix = new Matrix(new int[][] {{0, 0}, {0, 0}});
Собственно переменная matrix в этом тесте не нужна, можно просто вызвать конструктор и забить на его значение, раз мы всё равно ожидаем исключение.

2017-10-16 12:35 UTC, yurii-litvinov commented on hw2Gradle/src/test/java/ru/spbau/kirilenko/hw2MatrixTest/MatrixTest.java
> +        //assertArrayEquals(expectedAnswer, matrix.getSpiral());
Что-то пошло не так? :)

2017-10-16 12:35 UTC, yurii-litvinov commented on hw2Gradle/src/test/java/ru/spbau/kirilenko/hw2MatrixTest/MatrixTest.java
> +                                                {6, 1, 1}});
Без умаления общности матрица 
1 2 3
4 5 6
7 8 9
тоже подошла бы, а её проверять проще и понятнее

2017-10-16 12:35 UTC, yurii-litvinov commented on hw2Gradle/src/test/java/ru/spbau/kirilenko/hw2MatrixTest/MatrixTest.java
> +}
Я б ещё хотел тест на null-ы и сортировку матрицы из одного элемента

2017-10-23 16:43 UTC, Hotckiss commented on hw2Gradle/src/test/java/ru/spbau/kirilenko/hw2MatrixTest/MatrixTest.java
> +}
added

2017-10-31 12:48 UTC, yurii-litvinov approved these changes
Всё хорошо, зачтена

2017-10-31 12:48 UTC, yurii-litvinov commented on hw2Gradle/src/main/java/ru/spbau/kirilenko/hw2Matrix/Matrix.java
> +        if(inputMatrix == null) {
Пробел перед "(" надо :)

2017-11-06 22:09 UTC, merged