hw5MyZipFile
Hotckiss/Java-1 pull request #7
Opened 2017-10-10 21:42 UTC by Hotckiss

Unzip by regex class

2017-11-12 17:51 UTC, yurii-litvinov requested changes
В целом всё так, но исключения местами надо поправить

2017-11-12 17:51 UTC, yurii-litvinov commented on ZipFile/src/main/java/ru/spbau/kirilenko/hw4ZipFile/MyZipFile.java
> +            e.printStackTrace();
Лучше дать ему упасть или ловить, но в самом main-е. Иначе unzip запустится даже при неуспехе findFiles, а поскольку тут ловятся исключения вообще, а не какое-то конкретное исключение, то мы даже не знаем, в чём проблема, и программа потенциально в некорректном состоянии

2017-11-12 17:51 UTC, yurii-litvinov commented on ZipFile/src/main/java/ru/spbau/kirilenko/hw4ZipFile/MyZipFile.java
> +                        e.printStackTrace();
Тут тоже не очень хорошо исключение ловить (хотя и лучше, чем выше), так оно не видно из тестов

2017-11-12 17:51 UTC, yurii-litvinov commented on ZipFile/src/test/java/ru/spbau/kirilenko/hw4ZipFileTest/ZipFileTest.java
> +        }
Да пусть упадёт уж, это ж юнит-тест. Некому будет посмотреть на stack trace в консоли, если оно работает на CI-сервере

2017-11-12 17:51 UTC, yurii-litvinov commented on ZipFile/src/test/java/ru/spbau/kirilenko/hw4ZipFileTest/ZipFileTest.java
> +        Files.delete(path);
Если тест таки бросит исключение, то он не подчистит за собой, лучше для этого использовать `@After` или rules

2017-11-12 17:51 UTC, yurii-litvinov commented on ZipFile/src/test/java/ru/spbau/kirilenko/hw4ZipFileTest/ZipFileTest.java
> +    }
Ещё неплохо бы проверить, что ничего больше не распаковалось

2017-12-04 05:06 UTC, yurii-litvinov approved these changes
Теперь всё ок, зачтена

2017-12-04 05:06 UTC, yurii-litvinov commented on ZipFile/src/main/java/ru/spbau/kirilenko/hw4ZipFile/MyZipFile.java
> +                    os.close();
try-with-resources тут был бы лучше

2017-12-04 05:06 UTC, yurii-litvinov commented on ZipFile/src/test/java/ru/spbau/kirilenko/hw4ZipFileTest/ZipFileTest.java
> +        zos.close();
И тут. Ловить исключения в тестах не надо, но гарантированно закрывать файлы бло бы нелишне

2017-12-04 05:06 UTC, yurii-litvinov commented on ZipFile/src/test/java/ru/spbau/kirilenko/hw4ZipFileTest/ZipFileTest.java
> +    private final String dir = new String(System.getProperty("user.dir") + "/src/test/resources/");
Под виндой так не работает

2017-12-04 05:51 UTC, Hotckiss commented on ZipFile/src/test/java/ru/spbau/kirilenko/hw4ZipFileTest/ZipFileTest.java
> +    private final String dir = new String(System.getProperty("user.dir") + "/src/test/resources/");
Хм, у меня заработало когда запускал

2017-12-04 16:00 UTC, merged